In [2]:
!pip install numpy

In [3]:
import numpy as np

###
- create
- basic operation
- math operation
- indexing and slicing 
- boolean filter

In [4]:
x= np.array([1,2,3,4,5])
print(x)
print(x.shape)
print(type(x))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [5]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)
print(b.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9


In [7]:
z=[0,1,2,3,4,5,6,7,8,9]
nz=np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


###
- random
- arrange
- linespace

In [8]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
np.random.rand(3,3)

array([[0.53421836, 0.65413874, 0.53799176],
       [0.56720194, 0.16911963, 0.27912335],
       [0.8384584 , 0.10375626, 0.45840959]])

In [9]:
r1=np.random.randint(-5,6,size=(5,5)) #start value,end value,size=()
print(r1)

[[ 2  5  5  1  1]
 [ 0 -5  1  5 -4]
 [-5 -3  0 -1  4]
 [ 4 -1 -1  4 -5]
 [-4  4 -5 -4  1]]


In [10]:
#arange - start,end,interval
np.arange(0,50,.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5,
       44. , 44.5, 45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. ,
       49.5])

In [11]:
#Return evenly spaced numbers over a specified interval.
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

###
array attributes
- shape
- dtype
- ndim
- size

basic operations
- sum
- mean
- min
- max
- std
- reshape 
- transpose
- flatten

In [12]:
x

array([1, 2, 3, 4, 5])

In [13]:
x.dtype

dtype('int64')

In [14]:
x=np.random.rand(3,3)
print(x)
x.dtype

[[0.84449887 0.6403569  0.80206235]
 [0.0388043  0.92483042 0.74593705]
 [0.13674806 0.72215685 0.38793388]]


dtype('float64')

In [15]:
x.ndim  #tells about number of dimesntions array has

2

In [16]:
z=np.random.randint(1,5,size=(3,3,3))
print(z)
print(z.ndim)

[[[4 1 1]
  [1 4 1]
  [1 4 4]]

 [[2 1 4]
  [1 1 3]
  [2 3 1]]

 [[4 4 3]
  [2 2 2]
  [3 3 4]]]
3


In [17]:
z.size  #product of dims

27

In [18]:
a=np.random.random((2,3))
print(a.sum())
print(a.sum(axis=0))    #column wise
print(a.sum(axis=1))    #row wise

print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())
# all  methods can be used with axis

2.726231765780753
[0.5374806  1.06667169 1.12207947]
[1.04063262 1.68559915]
0.45437196096345883
0.9553188668324996
0.0025395435619470774
0.32464573563115817
0.10539485366349584


In [19]:
z=np.random.randint(11,99,size=(5,5))
print(z)

[[56 25 57 84 25]
 [34 14 97 66 97]
 [79 59 70 82 78]
 [53 46 32 94 52]
 [25 86 64 56 71]]


In [20]:
print('transpose')
print(z.transpose())

transpose
[[56 34 79 53 25]
 [25 14 59 46 86]
 [57 97 70 32 64]
 [84 66 82 94 56]
 [25 97 78 52 71]]


In [21]:
print('flattened')
print(z.flatten())

flattened
[56 25 57 84 25 34 14 97 66 97 79 59 70 82 78 53 46 32 94 52 25 86 64 56
 71]


In [22]:
a=np.random.randint(1,10,size=(4,5))
print(a)

[[8 4 7 4 2]
 [8 2 1 4 3]
 [8 9 5 2 9]
 [6 9 6 6 3]]


In [23]:
a

array([[8, 4, 7, 4, 2],
       [8, 2, 1, 4, 3],
       [8, 9, 5, 2, 9],
       [6, 9, 6, 6, 3]], dtype=int32)

In [24]:
#reshape is used to rehape any matrix into given dim
print(a.reshape(20))

[8 4 7 4 2 8 2 1 4 3 8 9 5 2 9 6 9 6 6 3]


In [25]:
print(a.reshape(5,4))


[[8 4 7 4]
 [2 8 2 1]
 [4 3 8 9]
 [5 2 9 6]
 [9 6 6 3]]


In [26]:
print(a.reshape(2,10))

[[8 4 7 4 2 8 2 1 4 3]
 [8 9 5 2 9 6 9 6 6 3]]


In [27]:
print(a.reshape(10,2))

[[8 4]
 [7 4]
 [2 8]
 [2 1]
 [4 3]
 [8 9]
 [5 2]
 [9 6]
 [9 6]
 [6 3]]


In [28]:
print(a.reshape(5,2,2))

[[[8 4]
  [7 4]]

 [[2 8]
  [2 1]]

 [[4 3]
  [8 9]]

 [[5 2]
  [9 6]]

 [[9 6]
  [6 3]]]


In [29]:
print(a)

[[8 4 7 4 2]
 [8 2 1 4 3]
 [8 9 5 2 9]
 [6 9 6 6 3]]


In [30]:
a=np.array([[1,2],[3,4]])
b=np.array([[6,2],[6,3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 2]
 [6 3]]


In [31]:
# when using 2 matrices, shpae must be same
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a@b)
print(a.dot(b))

[[7 4]
 [9 7]]
[[-5  0]
 [-3  1]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[ 6  4]
 [18 12]]
[[18  8]
 [42 18]]
[[18  8]
 [42 18]]


In [32]:
# when using matrix and scalar
print(a-10) #broadcasting
print(a*10) 
print(a/10)
print(a+10)

[[-9 -8]
 [-7 -6]]
[[10 20]
 [30 40]]
[[0.1 0.2]
 [0.3 0.4]]
[[11 12]
 [13 14]]


In [33]:
#indexing
print(a[0,0])
print(a[-1,-1])
print(b[1,1])

1
4
3


In [34]:
k=np.random.randint(0,10,(3,2,3))
print(k)

[[[7 0 2]
  [1 7 7]]

 [[3 6 9]
  [2 9 6]]

 [[7 8 7]
  [2 5 9]]]


In [35]:
print(k[2,0,2])

7


In [36]:
#slicing
np.random.seed(seed=342)    #seed to used to fix the random values
x=np.random.randint(1,10,size=(5,5))
print(x)

[[4 5 3 7 5]
 [5 4 3 1 7]
 [2 7 8 6 9]
 [7 9 5 4 8]
 [4 1 6 5 8]]


In [37]:
print(x[1,1:4])

[4 3 1]


In [38]:
print(x[:,0])   #select 0 index values from all rows(:)
print(x[:,-1])  #select -1 index values from all rows
print(x[:,:3])  #select 0:3 index values from all rows

[4 5 2 7 4]
[5 7 9 8 8]
[[4 5 3]
 [5 4 3]
 [2 7 8]
 [7 9 5]
 [4 1 6]]


boolean filter

In [39]:
x=np.arange(1,101).reshape(25,4)
x

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [ 13,  14,  15,  16],
       [ 17,  18,  19,  20],
       [ 21,  22,  23,  24],
       [ 25,  26,  27,  28],
       [ 29,  30,  31,  32],
       [ 33,  34,  35,  36],
       [ 37,  38,  39,  40],
       [ 41,  42,  43,  44],
       [ 45,  46,  47,  48],
       [ 49,  50,  51,  52],
       [ 53,  54,  55,  56],
       [ 57,  58,  59,  60],
       [ 61,  62,  63,  64],
       [ 65,  66,  67,  68],
       [ 69,  70,  71,  72],
       [ 73,  74,  75,  76],
       [ 77,  78,  79,  80],
       [ 81,  82,  83,  84],
       [ 85,  86,  87,  88],
       [ 89,  90,  91,  92],
       [ 93,  94,  95,  96],
       [ 97,  98,  99, 100]])

In [40]:
x>=50

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
x[x>=50]    #only value>=50

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [42]:
x[(x>=25) & (x<=75)]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])

some more operations

In [43]:
#The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(5,dtype=int) #dtype = int

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
np.diag([1,2,3,4]) #add given elements to matrix as diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [46]:
np.set_printoptions(precision=3)

In [47]:
np.random.rand(3,3)

array([[0.261, 0.765, 0.465],
       [0.006, 0.348, 0.575],
       [0.915, 0.738, 0.703]])

In [48]:
np.ones((3,5))  #make matrix of only 1's of given dim

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.zeros((3,5)) #make matrix of only 0's of given dim

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [50]:
np.sin(x)

array([[ 0.841,  0.909,  0.141, -0.757],
       [-0.959, -0.279,  0.657,  0.989],
       [ 0.412, -0.544, -1.   , -0.537],
       [ 0.42 ,  0.991,  0.65 , -0.288],
       [-0.961, -0.751,  0.15 ,  0.913],
       [ 0.837, -0.009, -0.846, -0.906],
       [-0.132,  0.763,  0.956,  0.271],
       [-0.664, -0.988, -0.404,  0.551],
       [ 1.   ,  0.529, -0.428, -0.992],
       [-0.644,  0.296,  0.964,  0.745],
       [-0.159, -0.917, -0.832,  0.018],
       [ 0.851,  0.902,  0.124, -0.768],
       [-0.954, -0.262,  0.67 ,  0.987],
       [ 0.396, -0.559, -1.   , -0.522],
       [ 0.436,  0.993,  0.637, -0.305],
       [-0.966, -0.739,  0.167,  0.92 ],
       [ 0.827, -0.027, -0.856, -0.898],
       [-0.115,  0.774,  0.951,  0.254],
       [-0.677, -0.985, -0.388,  0.566],
       [ 1.   ,  0.514, -0.444, -0.994],
       [-0.63 ,  0.313,  0.968,  0.733],
       [-0.176, -0.923, -0.822,  0.035],
       [ 0.86 ,  0.894,  0.106, -0.779],
       [-0.948, -0.245,  0.683,  0.984],
       [ 0.38 , 

In [51]:
arr2=np.random.randint(10,50,(4,4))
arr2

array([[27, 21, 23, 34],
       [24, 48, 22, 24],
       [31, 12, 10, 15],
       [48, 28, 17, 35]], dtype=int32)

In [52]:
print(arr2[0])
print(arr2[0,1])
print(arr2[-1])

[27 21 23 34]
21
[48 28 17 35]


In [53]:
print(arr2[:3])
print(arr2[1:])


[[27 21 23 34]
 [24 48 22 24]
 [31 12 10 15]]
[[24 48 22 24]
 [31 12 10 15]
 [48 28 17 35]]


In [54]:
arr2>20

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True, False,  True]])

In [55]:
y=arr2[arr2>20]
z=y.reshape(4,2)
print(z)

ValueError: cannot reshape array of size 12 into shape (4,2)

In [57]:
#Write a NumPy program to create an array of 10 zeros.
arr=np.zeros(10,dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
#Write a NumPy program to create an array of 10 ones.
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [59]:
np.random.randint(0,9,size=(3,3))

array([[8, 3, 2],
       [6, 3, 5],
       [6, 8, 2]], dtype=int32)

In [61]:
arr=np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [68]:
#Write a NumPy program to extract all odd numbers from an array.
arr=np.random.randint(100,size=10)
print(arr)
for i in  arr:
    
    if i%2!=0:
        print(i)


[74 87 98 18 24 19 50 86 61 74]
87
19
61


In [74]:
arr=np.random.rand(3,3)
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

4.529135081165946
0.5032372312406607
0.9075185113168961
0.0148089112331935
0.2987303964935012


In [81]:
#dot product
np.random.seed(23)
a=np.random.randint(10,size=(2,3))
b=np.random.randint(10,size=(2,3))
np.dot(a,b.T)   #dot product always works on matrix of shape A(a,b) & B(b,c) producing result of C(a,c)

array([[ 99,  40],
       [141,  76]], dtype=int32)

In [84]:
#print unique values using .unique fn
arr=np.random.randint(10,size=15)
print(arr)
unq=np.unique(arr)
print(unq)
    

[0 3 0 6 2 2 5 7 9 4 7 7 3 5 5]
[0 2 3 4 5 6 7 9]


In [88]:
#print unique values using normal iteration
arr=np.random.randint(10,size=15)
print(arr)
unq=[]
for i in arr:
    if i not in unq:
        unq.append(i)
unq=np.array(unq)
print(unq)

[4 0 6 9 8 0 1 6 2 0 0 0 2 2 6]
[4 0 6 9 8 1 2]


In [95]:
arr=np.random.randint(10,size=(3,5))
print(arr)
print(arr[:,::2])


[[4 9 5 6 1]
 [0 4 8 4 4]
 [5 4 8 5 0]]
[[4 5 1]
 [0 8 4]
 [5 8 0]]


In [98]:
arr=np.random.randint(10,size=(5,5))
print(arr)
print(arr[:3,:4])   #rows slicing, column slicing

[[1 7 7 1 0]
 [9 9 5 0 0]
 [4 3 0 8 9]
 [3 5 0 8 5]
 [7 7 1 7 5]]
[[1 7 7 1]
 [9 9 5 0]
 [4 3 0 8]]
